defmodule ChatF1Web.Schema.Types.ConversationTypes do
  @moduledoc "Absinthe type definitions for conversations, messages, and rate-limit status."

  use Absinthe.Schema.Notation

  @desc "The role of a message author."
  enum :message_role do
    value(:user, description: "A message sent by the viewer.")
    value(:assistant, description: "A response generated by the agent.")
  end

  @desc "Lifecycle status of a message."
  enum :message_status do
    value(:pending, description: "Placeholder created; agent call not yet started.")
    value(:streaming, description: "Agent is actively streaming (Phase 3 only).")
    value(:complete, description: "Message content is final.")
    value(:failed, description: "Agent call failed; content is the error summary.")
  end

  @desc "Source kind from retrieval pipeline."
  enum :source_kind do
    value(:vector, description: "Pinecone vector search result.")
    value(:web, description: "Tavily web search result.")
  end

  @desc "A retrieval source cited in an assistant response."
  object :source do
    field :kind, non_null(:source_kind)
    field :title, non_null(:string)
    field :url, :string
    field :snippet, :string
    field :score, :float
  end

  object :message do
    @desc "A single message in a conversation."
    field :id, non_null(:id)
    field :role, non_null(:message_role)
    field :content, non_null(:string)
    field :status, non_null(:message_status)
    field :intent, :string

    # The Ecto schema stores sources as a JSON column defaulting to %{}.
    # Without this resolver Absinthe list-wraps the bare map into [%{}] and
    # the non-null :kind crashes EVERY query selecting message.sources
    # (found in Phase 4 browser integration — sendMessage.userMessage died).
    # JSONB round-trips with string keys, so both key shapes are accepted.
    field :sources, non_null(list_of(non_null(:source))) do
      resolve(fn message, _args, _resolution ->
        {:ok, normalize_message_sources(message.sources)}
      end)
    end

    field :cached, non_null(:boolean)
    field :latency_ms, :integer
    field :inserted_at, non_null(:datetime)
  end

  @doc false
  def normalize_message_sources(sources) when is_list(sources) do
    Enum.map(sources, fn source ->
      %{
        kind: source_kind(source[:kind] || source["kind"]),
        title: source[:title] || source["title"] || "",
        url: source[:url] || source["url"],
        snippet: source[:snippet] || source["snippet"],
        score: source[:score] || source["score"]
      }
    end)
  end

  def normalize_message_sources(_), do: []

  defp source_kind(kind) when kind in [:web, "web"], do: :web
  defp source_kind(_), do: :vector

  object :conversation do
    @desc "A chat conversation owned by the viewer."
    field :id, non_null(:id)
    field :title, :string
    field :inserted_at, non_null(:datetime)

    field :messages, non_null(list_of(non_null(:message))) do
      arg(:first, :integer, default_value: 50)
      arg(:before, :string)

      resolve(fn conversation, args, _ ->
        messages = ChatF1.Conversations.list_messages(conversation.id)

        messages =
          if cursor = args[:before] do
            Enum.filter(messages, fn m -> to_string(m.id) < cursor end)
          else
            messages
          end

        limited = Enum.take(messages, args[:first])
        {:ok, limited}
      end)
    end
  end

  @desc "Payload returned by the sendMessage mutation."
  object :send_message_payload do
    field :user_message, non_null(:message)
    field :assistant_message_id, non_null(:id)
  end

  @desc "Current rate-limit status for the authenticated viewer."
  object :rate_limit_status do
    field :limit_per_minute, non_null(:integer)
    field :remaining_minute, non_null(:integer)
    field :limit_per_hour, non_null(:integer)
    field :remaining_hour, non_null(:integer)
    field :resets_at, non_null(:datetime)
  end

  # ─── Error types ─────────────────────────────────────────────────────────────

  @desc "Normalized error codes surfaced to GraphQL clients."
  enum :error_code do
    value(:upstream_unavailable,
      description: "The Python inference service is unreachable or returned an error."
    )

    value(:rate_limited,
      description: "The viewer has exceeded their request quota."
    )

    value(:budget_exhausted,
      description: "Daily LLM spend limit reached; SHOWCASE mode active (Phase 5)."
    )

    value(:validation,
      description: "Input failed validation (length, control chars, repetition)."
    )

    value(:internal,
      description: "Unexpected gateway or agent error."
    )
  end
end
